"""Payload obfuscation (planning.md 3.2).

Data tier: the encoder half. `web/src/data/codec.ts` is the decoder, and the
two must agree **byte for byte**.

    encode:  utf8(json) -> XOR with repeating key = utf8(dateISO) -> base64
    decode:  base64 -> XOR with same key -> utf8 -> JSON.parse

This is deliberately obfuscation, NOT encryption. It stops casual DevTools
snooping and shrinks the payload ~400x by shipping one day at a time. A
determined person still recovers it, and that is fine -- Wordle shipped its
entire word list in the bundle and survived. We are not pretending otherwise.

The cross-language risk is real and specific: UTF-8 multibyte handling, and
`atob` in JavaScript returning a *binary string* rather than bytes. Hence
`write_fixture` -- Python emits a payload the TypeScript suite must decode,
wired up before anything depends on the codec.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path


def xor_bytes(payload: bytes, key: bytes) -> bytes:
    """XOR `payload` against a repeating `key`. Its own inverse."""
    if not key:
        raise ValueError("codec key must not be empty")
    return bytes(b ^ key[i % len(key)] for i, b in enumerate(payload))


def encode(obj: object, key: str) -> str:
    """Object -> compact JSON -> XOR -> base64 ASCII.

    `sort_keys` and the tight separators keep output byte-stable so a
    regenerated archive diffs cleanly (planning.md 7.8).
    """
    raw = json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    scrambled = xor_bytes(raw.encode("utf-8"), key.encode("utf-8"))
    return base64.b64encode(scrambled).decode("ascii")


def decode(blob: str, key: str) -> object:
    """Inverse of `encode`. Present so the round-trip is testable in Python."""
    scrambled = base64.b64decode(blob.encode("ascii"))
    raw = xor_bytes(scrambled, key.encode("utf-8")).decode("utf-8")
    return json.loads(raw)


def write_fixture(path: Path) -> dict:
    """Emit the payload the TypeScript codec test must decode.

    Deliberately includes non-ASCII and characters that survive XOR into
    awkward byte values, because a codec that only works on plain ASCII will
    pass a naive test and fail on the first real puzzle.
    """
    sample = {
        "schemaVersion": 1,
        "id": 142,
        "date": "2027-02-19",
        "start": "apple",
        "end": "ocean",
        "solution": ["newton", "gravity", "moon", "tide"],
        "bank": [
            "pie", "gravity", "salt", "moon", "tide", "physics",
            "newton", "orbit", "wave", "cider", "comet",
        ],
        # Not shipped in real puzzles -- present purely to prove multibyte
        # UTF-8 survives the XOR/base64 round trip in both languages.
        "_utf8Probe": "café — naïve • 日本語 • 🎯",
    }
    key = sample["date"]
    fixture = {
        "note": "Generated by linkage. web/tests/codec.test.ts must decode this.",
        "key": key,
        "encoded": encode(sample, key),
        "expected": sample,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return fixture
